# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: heather.meatherall@ontariotechu.net
author_name: Heather
has_binder: true
has_settings: false
kind: frontend
labextension_name: feedback
project_short_description: A JupyterLab extension.
python_name: feedback
repository: https://github.com/Heather-meatherall/feedback
test: true

